### ISSUE TITLE
biased variance?

### ISSUE THREAD

**Issue by yangmr04** [computative/block#1]
Dear Marius,

This is Ray from Massey university, New Zealand. I am working on using quantum Monte Carlo (QMC) methods to solve quantum many-body problems. First of all, I am very impressed by your work on "Standard error estimation by an automated blocking method" and really grateful for your contribution to this area of knowledge. The "blocking method" is a very essential tool for processing my QMC data, and I am heavily relying on your hypothesis test to obtain standard errors. 

Here, I do have a question regarding the variance used in your code. I notice that you use the numpy function `var()` to compute the variance as shown here:
https://github.com/computative/block/blob/d5095fcfa266ded6282b300c0c67054495d87011/python/tictoc.py#L24
By default it has `ddof=0` which means the `var = sum((x-mu)**2)/n` where `n` is the length of the data points. For sample variance, this is biased (see [here](https://en.wikipedia.org/wiki/Variance#Population_variance_and_sample_variance)). Does it make scene to use `n-1` here to unbias it? 

Furthermore, for the autocovariance `gamma` here:
https://github.com/computative/block/blob/d5095fcfa266ded6282b300c0c67054495d87011/python/tictoc.py#L22
where γ(1) is computed. Should the first part be `(n-1)**(-1)` is used instead of `(n)**(-1)`? I understand that by definition it should be always dividing by 'n', but here I guess we want to have a more unbiased estimation for γ(1) for the hypothesis test, right?  
Seemingly you do this for the R version (I may be totally wrong here as I don't use R at all):
https://github.com/computative/block/blob/d5095fcfa266ded6282b300c0c67054495d87011/R/tinker.bell.R#L12
Moreover, does it make any sense to use `(n-1-1)` for further correction?

Could you please provide some insight into this? Really appreciate your help!

Many thanks,
Ray

**Comment by computative** [comment]
Dear Dr Yang,

(i) Yes, for gamma(h) it makes sense to pick n-p for any integer p << n. These are the so called shrinkage estimators. It is popular to pick p=h as it is also asymptotic MVUE. To my knowledge, they are not unbiased for n-h-1 in the case h>0. For variance, p=1 is popular for unbiased estimation, as you said.

(ii) For gamma(h) I want the prefactor to be n^(-1) for each h. I will make it consistent in the next update. Thanks for letting me know.

Kind regards,
Marius
